# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Daily

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  remove-old-releases:
    runs-on: ubuntu-latest
    steps:
      - uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 1
          delete_tags: true
          delete_tag_pattern: "-pre"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
